---
- name: Ensure locale is en_US.UTF-8
  lineinfile: dest=/etc/environment line=LANG=en_US.utf-8
  lineinfile: dest=/etc/environment line=LC_ALL=en_US.utf-8
  sudo: true

- name: Ensure git is installed
  apt: pkg=git state=latest
  sudo: true

- name: ensure requirements are installed
  apt: pkg={{ item }} state=latest
  sudo: true
  with_items:
    - gettext
