---
- name: Performs manage.py migrate
  when: deploy_migrate
  django_manage: >
      command=migrate
      app_path={{ deploy_path.stdout }}/git
      virtualenv={{ deploy_path.stdout }}/.virtualenv
