---
- name: Performs manage.py migrate
  when: deploy_migrate
  django_manage: >
      command=migrate
      app_path={{ deploy_path.stdout }}/git
      virtualenv=/home/{{ app_user }}/virtualenv
      settings=amiibofindr.settings.local

- name: Performs manage.py collectstatic
  django_manage: >
      command=collectstatic
      app_path={{ deploy_path.stdout }}/git
      virtualenv=/home/{{ app_user }}/virtualenv
      settings=amiibofindr.settings.local

- name: Performs manage.py compilemessages
  django_manage: >
      command=compilemessages
      app_path={{ deploy_path.stdout }}/git
      virtualenv=/home/{{ app_user }}/virtualenv
      settings=amiibofindr.settings.local
