---
- name: Create deploy folder
  file: path={{ app_builds_folder }}/{{ deploy_date.stdout }} state=directory

- action: shell echo {{ app_builds_folder }}/{{ deploy_date.stdout }}
  register: deploy_path
