---
- name: Ensure virtualenv requirements installed
  pip: requirements=/home/{{ app_user }}/git/requirements/production.txt
       virtualenv=/home/{{ app_user }}/virtualenv

# - name: Symlink virtualenv to git src folder
#   file: src=/home/{{ app_user }}/virtualenv
#         dest=/home/{{ app_user }}/git/.virtualenv
#         state=link
